### ISSUE TITLE
Get SoftSerial/Xbeeapi and sleepmode/powerdown to play nice

### ISSUE THREAD

**Issue by cujomalainey** [cujomalainey/Mass-Tach-Sensors#1]
Currently softserial/xbeeapi does not work when the unit is in powered down. The serial port my still be working but the data may not being transfered to the api. It will be very useful to get this working before the code gets to complex and before we true full 48 hour testing.

**Comment by dktrotti** [comment]
Tested current sensor code and found that this is not necessarily an issue for our uses. As the sensors will not need to receive unsolicited messages, we can simply keep the arduino and radio awake while a message is expected, and keep them asleep otherwise. This issue may be reopened if further development causes this issue to reappear.
